postprocess: {}
preprocess:
  add_flip_image: false
  crop:
  - 256
  - 256
  data_layout: NCHW
  pad_color: 0
  resize:
  - 256
  - 256
  resize_with_pad: false
  reverse_channels: false
session:
  artifacts_folder: artifacts
  input_data_layout: NCHW
  input_details:
  - name: input.1Net_IN
    shape:
    - 1
    - 3
    - 256
    - 256
    type: tensor(uint8)
  input_mean: null
  input_optimization: true
  input_scale: null
  model_folder: model
  model_path: model/midas-small.onnx
  output_details:
  - name: '983'
    shape:
    - 1
    - 1
    - 256
    - 256
    type: tensor(float)
  run_dir: de-7310_onnxrt_nyudepthv2_MiDaS_midas-small_onnx
  session_name: onnxrt
  runtime_options: 
    advanced_options:output_feature_16bit_names_list: 511, 983
    accuracy_level: 1                                                                              
    advanced_options:activation_clipping: 1                                                        
    advanced_options:add_data_convert_ops: 3                                                       
    advanced_options:bias_calibration: 1                                                           
    advanced_options:calibration_frames: 25                                                        
    advanced_options:calibration_iterations: 25                                                    
    advanced_options:channel_wise_quantization: 0                                                  
    advanced_options:high_resolution_optimization: 0                                               
    advanced_options:params_16bit_names_list: ''                                                   
    advanced_options:pre_batchnorm_fold: 1                                                         
    advanced_options:quantization_scale_type: 1                                                    
    advanced_options:weight_clipping: 1       
  target_device: AM62A
task_type: depth_estimation
