postprocess: {}
preprocess:
  add_flip_image: false
  crop:
  - 224
  - 224
  data_layout: NCHW
  pad_color: 0
  resize:
  - 224
  - 224
  resize_with_pad: false
  reverse_channels: false
session:
  artifacts_folder: artifacts
  input_data_layout: NCHW
  input_details:
  - name: input.1
    shape:
    - 1
    - 3
    - 224
    - 224
    type: tensor(float32)
  input_mean:
  - 0
  - 0
  - 0   
  input_scale: 
  - 0.00392157
  - 0.00392157
  - 0.00392157
  input_optimization: false
  model_folder: .
  model_path: fastdepth-shape.onnx
  output_details:
  - name: 424
    shape:
    - 1
    - 1
    - 224
    - 224
    type: tensor(float32)
  session_name: onnxrt
  target_device: AM62A
task_type: segmentation
